Repository rickbusarow/ModuleCheck, pull requests merged in 2022-04, with the labels that each got.

#491 update KtLint to 45.1
  .gitignore
  .idea/ktlint.xml
  build-logic/mcbuild/src/main/kotlin/mcbuild.ktlint.gradle.kts
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/FindingResultFactory.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/kapt/KaptMatchers.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyPluginsBlockParserTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinPluginsBlockParserTest.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealDependenciesBlocksProvider.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/AndroidPlatformPluginFactory.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/BasePluginTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/ConfigValidationTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/factories.kt
  modulecheck-reporting/graphviz/src/main/kotlin/modulecheck/reporting/graphviz/GraphvizFactory.kt
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectBuildSpec.kt
Labels: automerge

#492 update Gradle to 7.4.2
  .github/workflows/ci.yml
  gradle/wrapper/gradle-wrapper.properties
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectBuildSpec.kt
Labels: dependencies, automerge

#493 `DeclarationName` -> `DeclaredName` rename cleanup
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidDataBindingDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidViewBindingDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ResolvedDeclaredNames.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/RealJavaFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/DeclarationVisitor.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/psiElement.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceDeclaredName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclaredName.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealMcProject.kt
Labels: automerge

#495 better McProject integration in parsing tests
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/GraphVizReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKotlinAndroidExtensionsTest.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
Labels: automerge

#496 update Kotlin to 1.6.20
  .github/workflows/ci.yml
  dependabot-bridge/build.gradle.kts
  gradle/libs.versions.toml
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectBuildSpec.kt
Labels: dependencies, automerge

#497 DeclaredName cleanup #3
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidRDeclaredNames.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclaredNames.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceReferences.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/Declarations.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclaredName.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/UnqualifiedAndroidResourceDeclarationTest.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/McProject.kt
Labels: automerge

#499 count layout files and `@+id/__` declarations as part of a module's declarations
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclaredNames.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/XmlFile.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/XmlFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceDeclaredName.kt
Labels: automerge, bugfix

#500 introduce `AndroidResourceReference` types
  .idea/ktlint.xml
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/TestJavaFile.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceDeclaredName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/Reference.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/BaseNamedSymbolTest.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/DeclaredNameTest.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/ReferenceTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilder.kt
Labels: automerge

#504 some `DisableAndroidResources` fixes
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableAndroidResourcesRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
Labels: automerge

#505 check for the `-SNAPSHOT` version suffix in CI
  .github/workflows/ci.yml
  build-logic/mcbuild/src/main/kotlin/modulecheck/builds/publishing.kt
Labels: automerge

#506 remove debugging println from XmlFile
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/XmlFile.kt
Labels: automerge

#507 java parsing cleanup
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/ParsedFile.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/RealJavaFile.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
Labels: automerge

#509 better modeling for generated databinding declarations and references
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidDataBindingDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclaredNames.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceReferences.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidViewBindingDeclarations.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/MustBeApi.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableAndroidResourcesRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableViewBindingRule.kt
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/XmlFile.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/psiElement.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceDeclaredName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceReference.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclaredName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/Reference.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/internal/AndroidDataBindingNameProvider.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/BaseNamedSymbolTest.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/DeclaredNameTest.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/ReferenceTest.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/AndroidDataBindingReferenceParsingInterceptor.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/AndroidResourceReferenceParsingInterceptor.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealAndroidDataBindingNameProvider.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealAndroidRNameProvider.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealJvmFileProvider.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/factories.kt
Labels: automerge, bugfix

#510 Fix false positive for `unusedDependency` when a resource from the dependency is used with R from the dependent in a downstream project
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclaredNames.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidUnqualifiedDeclarationNames.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/internal/uses.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AndroidResourceDeclaredName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclaredName.kt
  modulecheck-parsing/source/src/test/kotlin/modulecheck/parsing/source/DeclaredNameTest.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/LazySet.kt
Labels: automerge, bugfix

#513 fix extra line after generated `android { ... }` block
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/android/UnusedResourcesGenerationFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
Labels: automerge

#515 skip generating/parsing transient Android resource declarations if `nonTransientRClass` is enabled
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclaredNames.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/internal/uses.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/PlatformPlugin.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/AndroidPlatformPluginFactory.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/PlatformPluginBuilder.kt
Labels: automerge

#517 add contributors to the changelog template
  .github/release-drafter.yml
Labels: automerge

#516 support multiple Java variable declarations in a single line
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/ParsedFile.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/visitor.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
Labels: automerge

#518 track resource references made within an Android style declaration
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceReferences.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidStylesFiles.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/References.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/AndroidStylesFile.kt
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/AndroidStylesParser.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/StylesFileTest.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/ParsedFile.kt
Labels: automerge

#522 don't try to parse `.png`s as xml
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/SafeXmlParser.kt
Labels: automerge, bugfix

#523 don't version the website for SNAPSHOT versions
  build-logic/mcbuild/src/main/kotlin/mcbuild.website.gradle.kts
Labels: automerge

#525 add more exclusions to the ci matrix
  .github/workflows/ci.yml
Labels: automerge

#521 Don't call a dependency overshot if it's already declared in that source set
  modulecheck-core/src/main/kotlin/modulecheck/core/context/OverShotDependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ConfiguredProjectDependency.kt
Labels: automerge, bugfix

#527 disable parallel tests in the plugin module
  modulecheck-plugin/build.gradle.kts
Labels: automerge

#419 Add a test case for false positive
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidUnqualifiedDeclarationNames.kt
  modulecheck-parsing/gradle/build.gradle.kts
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/PlatformPlugin.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/AndroidPlatformPluginFactory.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/UnusedDependenciesPluginTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/PlatformPluginBuilder.kt
Labels: automerge, bugfix

#529 update ktlint to 0.45.2
  build-logic/mcbuild/src/main/kotlin/mcbuild.ktlint.gradle.kts
Labels: dependencies, automerge

#530 remove modified dependencies via comment if `deleteUnused` is disabled
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Deletable.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Finding.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/FindingResultFactory.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Fixable.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/internal/dependencies.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/internal/mcProject.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/internal/string.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/AbstractProjectDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/InheritedDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/MustBeApiFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/OverShotDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/RedundantDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/UnusedDependency.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/UnusedPluginFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/OverShotDependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/kapt/UnusedKaptProcessorFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/MultiRuleFindingFactory.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/OverShotDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/android/DisableViewBindingGenerationFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/android/UnusedResourcesGenerationFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/sort/SortDependenciesFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/sort/SortPluginsFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependenciesBlock.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/collection.kt
Labels: automerge

#535 better strategy for `kotlinStdLibNameOrNull`
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/kotlinStdLibNames.kt
Labels: automerge

#536 Exhaustive assertions against files in KotlinFileTest
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/FancyShould.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/ktCallableDeclaration.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/psiElement.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/kotlinStdLibNames.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/internal/NameParser.kt
  modulecheck-parsing/source/src/testFixtures/kotlin/modulecheck/parsing/test/NamedSymbolTest.kt
Labels: automerge

#458 disable configuration caching until it's actually supported
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/ModuleCheckPlugin.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/task/ModuleCheckTask.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/TasksValidationTest.kt
Labels: automerge

#538 add a change's author to its change log entry
  .github/release-drafter.yml
Labels: automerge

#539 add "new rules" to CL template
  .github/release-drafter.yml
Labels: automerge

#540 update Docusaurus to `2.0.0-beta.18`
  website/package.json
  website/yarn.lock
Labels: automerge

#541 add `/website` to Dependabot's update checks
  .github/dependabot.yml
Labels: automerge

#542 prioritize "new rule" over "features" in release drafter
  .github/release-drafter.yml
Labels: automerge

#555 add missing docs for rules
  modulecheck-api/src/main/kotlin/modulecheck/api/rule/ModuleCheckRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/AnvilFactoryRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DepthRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableAndroidResourcesRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableViewBindingRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DocumentedRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/MustBeApiRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/OverShotDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/RedundantRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/SortDependenciesRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/SortPluginsRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedKaptRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedKotlinAndroidExtensionsRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/RuleUrlValidationTest.kt
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/reflection.kt
  website/docs/rules/android/unused_kotlin_android_extensions.md
  website/docs/rules/compiler/could_use_anvil_factory.md
  website/docs/rules/kapt/unused_kapt_plugin.md
  website/docs/rules/kapt/unused_kapt_processor.md
  website/docs/rules/must_be_api.md
  website/docs/rules/overshot_dependency.md
  website/docs/rules/redundant_dependency.md
  website/docs/rules/unused.md
  website/sidebars.js
  website/versioned_docs/version-0.12.0/rules/compiler/could_use_anvil_factory.md
  website/versioned_docs/version-0.12.0/rules/kapt/unused_kapt_plugin.md
  website/versioned_docs/version-0.12.0/rules/must_be_api.md
  website/versioned_docs/version-0.12.0/rules/overshot_dependency.md
  website/versioned_docs/version-0.12.0/rules/redundant_dependency.md
  website/versioned_sidebars/version-0.12.0-sidebars.json
  website/yarn.lock
Labels: documentation, automerge

#559 add `google()` repository to config docs
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/ConfigValidationTest.kt
  website/docs/quickstart.mdx
  website/versioned_docs/version-0.12.0/quickstart.mdx
Labels: documentation, automerge

#560 revert mdx update and ensure that website builds as part of CI
  .github/workflows/ci.yml
  website/package.json
  website/yarn.lock
Labels: automerge

#565 move `File.createSafely()` to production code
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/file.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/AndroidResourceParserTest.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/SafeXmlParserTest.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/StylesFileTest.kt
  modulecheck-parsing/android/src/test/kotlin/modulecheck/parsing/android/XmlFileTest.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyPluginsBlockParserTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AndroidBuildConfigAvoidanceTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/ConfigValidationTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/DepthReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/GraphReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/TasksValidationTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/factories.kt
  modulecheck-runtime/src/main/kotlin/modulecheck/runtime/ModuleCheckRunner.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/file.kt
Labels: automerge, chore

#567 standardize hermit's definition in `libs.versions.toml`
  gradle/libs.versions.toml
Labels: automerge, chore

#568 add Detekt's SARIF reports to CI
  .github/workflows/ci.yml
  build-logic/mcbuild/src/main/kotlin/mcbuild.detekt.gradle.kts
Labels: automerge, chore
