Repository rickbusarow/ModuleCheck, pull requests merged in 2022-03, with the labels that each got.

#420 parse console output into pojos in tests
  modulecheck-core/src/test/kotlin/modulecheck/core/CheckstyleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/ConsoleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthOutputTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/GraphVizReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortPluginsTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/TextReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/BaseTest.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyPluginsBlockParserTest.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/JavaEverythingPrinter.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/BasePluginTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/TasksValidationTest.kt
  modulecheck-reporting/checkstyle/build.gradle.kts
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/ReportFactory.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/ProjectFindingReport.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/RunnerTest.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/outputParsing.kt
Labels: automerge

#422 add configuration to output
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Finding.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Fixable.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/AbstractProjectDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/kapt/UnusedKaptProcessorFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/CheckstyleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/ConsoleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthOutputTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/TextReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AnvilScopesTest.kt
  modulecheck-reporting/checkstyle/src/test/kotlin/modulecheck/reporting/checkstyle/CheckstyleReporterTest.kt
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/ReportFactory.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/ProjectFindingReport.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/outputParsing.kt
Labels: automerge

#423 remove `trimmedShouldBe` from failed test stacktraces
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/BaseTest.kt
Labels: automerge

#428 add the `File.shouldHaveText` assertion
  modulecheck-core/src/test/kotlin/modulecheck/core/CheckstyleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/GraphVizReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortPluginsTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/BaseTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/DepthReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/GraphReportTaskTest.kt
Labels: automerge

#429 add a lambda for writing `buildFile` content
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthOutputTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortPluginsTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/DepthReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/GraphReportTaskTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilderScope.kt
Labels: automerge

#431 delete the unused `ClassPaths` context element
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ClassPaths.kt
Labels: automerge

#432 rename `toSourceSetName` to `asSourceSetName`
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/Config.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/SourceSet.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/project.kt
Labels: automerge

#430 use java 11 for source
  build-logic/mcbuild/src/main/kotlin/mcbuild.java-library.gradle.kts
  build-logic/mcbuild/src/main/kotlin/mcbuild.kotlin.gradle.kts
  modulecheck-plugin/build.gradle.kts
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/ModuleCheckExtension.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/ModuleCheckPlugin.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/project.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/sourceSets.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/task/ModuleCheckTask.kt
Labels: automerge

#435 refine replacing configuration names when using string extension invocations
  modulecheck-core/src/main/kotlin/modulecheck/core/InheritedDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/MustBeApiFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/McProject.kt
Labels: automerge

#436 clean up upstream/downstream handling for Config
  modulecheck-core/src/main/kotlin/modulecheck/core/context/OverShotDependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/Config.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/SourceSet.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/Configurations.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/AndroidMcProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilderScope.kt
Labels: automerge

#437 detect the test fixtures toggle from the android dsl
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/UnusedDependenciesPluginTest.kt
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectBuildSpec.kt
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectSrcSpec.kt
Labels: automerge

#438 finish updating everything to java 11
  build-logic/build.gradle.kts
  build-logic/mcbuild/build.gradle.kts
  build-logic/mcbuild/src/main/kotlin/mcbuild.java-library.gradle.kts
  build-logic/mcbuild/src/main/kotlin/mcbuild.kotlin.gradle.kts
  build-logic/mcbuild/src/main/kotlin/modulecheck/builds/catalogs.kt
Labels: automerge

#442 better handling for detecting complex precompiled configuration names
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/SourceSet.kt
Labels: automerge, bugfix

#444 don't swallow a newline when replacing a dependency with a preceding blank line
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/dependencies.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
Labels: automerge, bugfix

#439 update Gradle to 7.4.1
  .github/workflows/ci.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  modulecheck-specs/src/main/kotlin/modulecheck/specs/ProjectBuildSpec.kt
Labels: dependencies, automerge

#445 better `mustBeApi` handling for overshot and inherited findings
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AnvilGraph.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/Declarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ResolvedDeclarationNames.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/MustBeApi.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/OverShotDependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/SourceSet.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/JvmFile.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ConfiguredProjectDependency.kt
Labels: automerge

#446 fix false positive for `disableViewBinding` when used in debug source set of different module
  modulecheck-api/src/main/kotlin/modulecheck/api/context/DownstreamProjects.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableViewBindingRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ConfiguredProjectDependency.kt
Labels: automerge, bugfix

#451 better modeling of SourceSets
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/GraphVizReportTest.kt
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/asserts.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/Config.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/ConfigFactory.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/SourceSet.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/Configurations.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/sourcesets/AndroidSourceSetsParser.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/sourcesets/GradleSourceSetName.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/sourcesets/JvmSourceSetParser.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/AndroidMcProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/sourceSets.kt
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/DepthReportFactory.kt
  modulecheck-reporting/graphviz/src/main/kotlin/modulecheck/reporting/graphviz/GraphvizFileWriter.kt
Labels: automerge

#452 consume sourceSet changes in rules
  modulecheck-core/src/main/kotlin/modulecheck/core/internal/uses.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/MultiRuleFindingFactory.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/MustBeApiRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclarationName.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/UnusedDependenciesPluginTest.kt
Labels: automerge

#448 ClasspathDependencies cleanup
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ClasspathDependencies.kt
Labels: automerge

#455 fix parsing fully qualified references in java files
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/RealJavaFile.kt
Labels: automerge

#456 make unit tests run in parallel
  build-logic/mcbuild/src/main/kotlin/mcbuild.test.gradle.kts
Labels: automerge

#457 differentiate between Kotlin and Java names when parsing Kotlin files
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceReferences.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AnvilGraph.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/anvil/AnvilFactoryParser.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/MustBeApi.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/internal/uses.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableViewBindingRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedKaptRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedKotlinAndroidExtensionsRule.kt
  modulecheck-parsing/android/src/main/kotlin/modulecheck/parsing/android/XmlFile.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/ParsedFile.kt
  modulecheck-parsing/java/src/main/kotlin/modulecheck/parsing/java/RealJavaFile.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/JavaFileTest.kt
  modulecheck-parsing/java/src/test/kotlin/modulecheck/parsing/java/TestJavaFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/FqNames.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/ReferenceVisitor.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/ktCallableDeclaration.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/psiElement.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/AnvilGradlePlugin.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/DeclarationName.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/JvmFile.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/NamedSymbol.kt
  modulecheck-parsing/source/src/main/kotlin/modulecheck/parsing/source/Reference.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/LazySet.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/LazySetImpl.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/flow.kt
Labels: automerge

#454 Add documentation for new rule
  website/docs/configuration.mdx
  website/docs/rules/android/unused_kotlin_android_extensions.md
Labels: documentation, automerge

#463 force single-threaded GroovyLangParser access
  modulecheck-internal-testing/src/main/kotlin/modulecheck/testing/asserts.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParser.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyParsingScope.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyPluginsBlockParser.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyPluginsBlockParserTest.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealDependenciesBlocksProvider.kt
  modulecheck-parsing/wiring/src/main/kotlin/modulecheck/parsing/wiring/RealPluginsBlockProvider.kt
Labels: automerge, bugfix

#464 rename `moduleAccess` to `projectAccessor`
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependenciesBlock.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/gradle/src/testFixtures/kotlin/modulecheck/parsing/gradle/ReportingLogger.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParser.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParser.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
Labels: automerge

#465 use strong typing for `McProject.path`
  modulecheck-api/src/main/kotlin/modulecheck/api/DepthFinding.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ClasspathDependencies.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/DependencySources.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Finding.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/Fixable.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/AbstractProjectDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/InheritedDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/MustBeApiFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/OverShotDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/RedundantDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/UnusedPluginFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/anvil/CouldUseAnvilFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/context/UnusedDependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/kapt/UnusedKaptProcessorFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/InheritedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/OverShotDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedDependencyRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/android/DisableViewBindingGenerationFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/android/UnusedResourcesGenerationFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/sort/SortDependenciesFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/sort/SortPluginsFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/CheckstyleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/ConsoleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/TextReportingTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependenciesBlock.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/ProjectPath.kt
  modulecheck-parsing/gradle/src/testFixtures/kotlin/modulecheck/parsing/gradle/ReportingLogger.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParser.kt
  modulecheck-parsing/groovy-antlr/src/test/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParserTest.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParser.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ConfiguredProjectDependency.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ProjectCache.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/ProjectProvider.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/AndroidMcProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealAndroidMcProject.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealMcProject.kt
  modulecheck-reporting/checkstyle/src/main/kotlin/modulecheck/reporting/checkstyle/CheckstyleReporter.kt
  modulecheck-reporting/checkstyle/src/test/kotlin/modulecheck/reporting/checkstyle/CheckstyleReporterTest.kt
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/DepthLogFactory.kt
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/DepthReportFactory.kt
  modulecheck-reporting/console/src/main/kotlin/modulecheck/reporting/console/ReportFactory.kt
  modulecheck-reporting/graphviz/src/main/kotlin/modulecheck/reporting/graphviz/GraphvizFactory.kt
Labels: automerge

#468 add ProjectAccessor type
  modulecheck-core/src/test/kotlin/modulecheck/core/SortDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependenciesBlock.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/ProjectAccessor.kt
  modulecheck-parsing/gradle/src/testFixtures/kotlin/modulecheck/parsing/gradle/ReportingLogger.kt
  modulecheck-parsing/groovy-antlr/src/main/kotlin/modulecheck/parsing/groovy/antlr/GroovyDependencyBlockParser.kt
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParser.kt
Labels: automerge

#470 don't generate BuildConfig if it's ignored in Android settings
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/ModuleCheckPlugin.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/project.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AndroidBuildConfigAvoidanceTest.kt
Labels: automerge, bugfix

#469 add new dependency declarations even if their transitive source can't be found
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/dependencies.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/InheritedDependencyFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/MustBeApiFinding.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/OverShotDependencyFinding.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/BuildFileParser.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/ProjectPath.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AnvilScopesTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/UnusedDependenciesPluginTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/jvmSubProject.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/McProject.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/AndroidMcProjectBuilderScope.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealAndroidMcProject.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealMcProject.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/apply.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/comparable.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/string.kt
Labels: automerge, bugfix

#471 clean up Dokka task dependencies and disable configuration cache for …
  build-logic/mcbuild/src/main/kotlin/mcbuild.dokka.gradle.kts
  build-logic/mcbuild/src/main/kotlin/modulecheck/builds/publishing.kt
Labels: automerge

#472 override `ProjectPath.toString()`
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/ProjectPath.kt
Labels: automerge

#473 better build/platform plugin modeling
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidBasePackages.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidDataBindingDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidRFqNames.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceDeclarations.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/AndroidResourceReferences.kt
  modulecheck-api/src/main/kotlin/modulecheck/api/context/ManifestFiles.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableAndroidResourcesRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/DisableViewBindingRule.kt
  modulecheck-core/src/main/kotlin/modulecheck/core/rule/UnusedKotlinAndroidExtensionsRule.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthOutputTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKotlinAndroidExtensionsTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/InvokesConfigurationNames.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/PlatformPlugin.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/PluginAware.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinDependencyBlockParserTest.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/AndroidPlatformPluginFactory.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/ConfigurationsFactory.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/GradleProjectProvider.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/JvmPlatformPluginFactory.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/SourceSetsFactory.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/project.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/sourcesets/AndroidSourceSetsParser.kt
  modulecheck-plugin/src/main/kotlin/modulecheck/gradle/internal/sourcesets/JvmSourceSetParser.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/Logger.kt
  modulecheck-project/api/src/main/kotlin/modulecheck/project/McProject.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/AndroidMcProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ConfigBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/McProjectBuilderScope.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/PlatformPluginBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/SourceSetBuilder.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/factories.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/sourceSets.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealAndroidMcProject.kt
  modulecheck-project/impl/src/main/kotlin/modulecheck/project/impl/RealMcProject.kt
  modulecheck-reporting/graphviz/src/main/kotlin/modulecheck/reporting/graphviz/GraphvizFileWriter.kt
  modulecheck-runtime/src/testFixtures/kotlin/modulecheck/runtime/test/RunnerTest.kt
Labels: automerge

#474 add special handling for `is-` prefixes in Kotlin -> Java interop
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/internal/ktCallableDeclaration.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
Labels: automerge

#475 remove deprecated `project` and `androidProject` functions
  modulecheck-core/src/test/kotlin/modulecheck/core/CheckstyleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/ConsoleReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthOutputTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DepthReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableAndroidResourcesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/DisableViewBindingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/GraphVizReportTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/MustBeApiTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/OverShotDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/SortPluginsTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/TextReportingTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedDependenciesTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKaptProcessorTest.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/UnusedKotlinAndroidExtensionsTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AndroidBuildConfigAvoidanceTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/AnvilScopesTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/ConfigValidationTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/DepthReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/GraphReportTaskTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/TasksValidationTest.kt
  modulecheck-plugin/src/test/kotlin/modulecheck/gradle/UnusedDependenciesPluginTest.kt
  modulecheck-project/api/src/testFixtures/kotlin/modulecheck/project/test/ProjectTest.kt
Labels: automerge

#477 resolve import aliases in Kotlin files
  modulecheck-parsing/psi/src/main/kotlin/modulecheck/parsing/psi/RealKotlinFile.kt
  modulecheck-parsing/psi/src/test/kotlin/modulecheck/parsing/psi/KotlinFileTest.kt
Labels: automerge

#478 fix inheritedDependency auto-correct when the source has a config block
  modulecheck-api/src/main/kotlin/modulecheck/api/finding/dependencies.kt
  modulecheck-core/src/test/kotlin/modulecheck/core/InheritedDependenciesTest.kt
  modulecheck-parsing/gradle/src/main/kotlin/modulecheck/parsing/gradle/DependencyDeclaration.kt
  modulecheck-utils/src/main/kotlin/modulecheck/utils/string.kt
Labels: automerge
